<?php defined('SYSPATH') or die('No direct script access.');

// This file was generated by Kohana-I18nget, http://github.com/rafsoaken/kohana-i18nget

return array(
	// \views\user\login.php
	'login' => 'Login', // 16
	'email.or.username' => 'Email oder Username', // 23
	'password' => 'Passwort', // 26
	'?forgot.password' => '', // 27
	'remember.me' => 'Anmeldung merken', // 36
	'?dont.have.account' => 'Sie sind noch nicht registriert?', // 50
	'register.new.account' => 'Neuen User registrieren', // 50
	'register.or.providerchange' => 'Zur Registration / zum Anmelden klicken Sie bitte auf Ihren Konto Provider', // 53

	// \views\user\noaccess.php
	'access.denied' => 'Keine Zugriffsberechtigung', // 2
	'no.rights.to.access.functionality' => 'Sie haben für diese Funktion nicht die erforderlichen Rechte', // 4

	// \views\user\profile.php
	'edit.profile' => 'Profil bearbeiten', // 4
	'delete.account' => 'Konto löschen', // 5
	'user.profile' => 'User Profil', // 9
	'your.user.information' => 'Ihr Benutzerkonto', // 11
	'username' => 'Username', // 13
	'email' => 'Email', // 13
	'login.activity' => 'Login Aktivität', // 16
	'total.nbr.logins' => 'Anzahl aller Logins', // 17
	'accounts.associated.with.profile' => 'Konten, die mit diesem Profil verbunden sind', // 23
	'additional.accountproviders' => 'Weitere Konten Provider', // 31
	'click.provider.icon.to.associate.account' => 'Klicken Sie das Konto Provider Logo um Ihr Profil damit zu verknüpfen', // 31

	// \views\user\profile_edit.php
	'roles' => 'Berechtigungen', // 19
	'role' => 'Berechtigung', // 21
	'description' => 'Beschreibung', // 21
	'save' => 'Speichern', // 40

	// \views\user\register.php
	'register' => 'Registrieren', // 3
	'?already.have.account' => 'Haben Sie schon ein Konto?', // 5
	'login.here' => 'Hier anmelden', // 5
	'enter.info.to.register' => 'Füllen Sie folgende Informationen aus, um sich zu registrieren', // 7
	'register.account' => 'Neues Benutzerkonto anlegen', // 35

	// \views\user\user_edit_form.php
	'allowed.usernames' => 'Länge zw. 4 bis 32 Buchstaben oder Zahlen', // 2
	'email.address' => 'Email Adresse', // 3
	'allowed.passwords' => 'Passwörter sollten zwischen 6 und 42 Zeichen lang sein', // 6
	'retype.password' => 'Passwort wiederholen', // 7

	// \views\user\reset\forgot.php
	'?forgot.password.or.username' => 'Usernamen oder Passwort vergessen?', // 3
	'send.password.resetlink' => 'Passwort-zurücksetzen Link schicken', // 5
	'reset.password' => 'Passwort zurücksetzen', // 12

	// \views\user\reset\reset.php
	'account.email.address' => 'Benuzterkonto Email Adresse', // 9
	'password.reset.token' => 'Passwort-Reset Kennung', // 13

	// \views\user\admin\delete.php
	'?delete.user' => 'User löschen?', // 2
	'?sure.to.delete.user' => 'User wirklich löschen?', // 10
	'yes' => 'Ja', // 12
	'no' => 'Nein', // 13
	'delete' => 'löschen', // 14
	'cancel' => 'abbrechen', // 18

	// \views\user\admin\edit.php
	'?edit.or.add.user' => 'User editieren oder hinzufügen?', // 18

	// \views\user\admin\index.php
	'?add.user' => 'User hinzufügen?', // 11
	'administer.users' => 'User verwalten', // 15
	'edit' => 'Editieren', // 31
	'last.login' => 'Letztes Login', // 54
	'nbr.of.logins' => 'Anzahl der Logins', // 55
	'identities' => 'Identitäten', // 58
	'actions' => 'Aktionen', // 60

	// \views\template\useradmin.php
	'user.admin' => 'User Admin', // 20
	'my.profile' => 'Mein Profil', // 21
	'logout' => 'Abmelden', // 22

	// \views\pagination\useradmin.php
	'first' => 'Erste', // 13
	'previous' => 'Folgende', // 19
	'next' => 'Nächste', // 35
	'last' => 'Letzte', // 41

	// \classes\useradmin\helper\format.php
	'never' => 'nie', // 33
	'one.second.ago' => 'vor einer Sekunde', // 38
	'seconds.ago' => 'Sekunden zuvor', // 38
	'one.minute.ago' => 'vor einer Minute', // 42
	'minutes.ago' => 'Minuten zuvor', // 46
	'one.hour.ago' => 'vor einer Stunde', // 50
	'hours.ago' => 'Stunden zuvor', // 54
	'yesterday' => 'gestern', // 58
	'days.ago' => 'Tage zuvor', // 62
	'one.month.ago' => 'vor einem Monat', // 67
	'months.ago' => 'Monate zuvor', // 67
	'one.year.ago' => 'vor einem Jahr', // 72
	'years.ago' => 'Jahre zuvor', // 72

	// \classes\useradmin\controller\user.php
	'values.saved' => 'Werte gespeichert', // 161
	'error.values.could.not.be.saved' => 'Error. Werte konnten nicht gespeichert werden', // 170
	'user.registration' => 'Benutzer registrieren', // 208
	'captcha.incorrect' => 'Captcha ist nicht korrekt', // 235
	'please.try.again' => 'Bitte versuchen Sie es nochmals', // 235
	'close.user.account' => 'Dieses Benutzerkonto schließen', // 277
	'user.deleted' => 'Benuter wurde gelöscht', // 306
	'forgot.password' => 'Passwort vergessen', // 420
	'account.password.reset' => 'Benutzerkonto Passwort zurücksetzen', // 435
	'email.password.reset.message.body' => 'Sie haven ein Passwort-Reset auf unserer Seite angefragt.

    Sie können jetzt Ihr Passwort zurücksetzen, indem Sie diesen Link aufrufen:

:reset_token_link

Falls der Link nicht geklickt werden kann, kopieren Sie bitte folgenden Link in Ihren Browser:

:reset_link

Und dann kopieren Sie bitte die Reset Kennung :reset_token in das vorgesehene Feld.
Ihr Benutzername ist: :username

', // 438
	'password.reset.email.sent' => 'Ein Email mit einem Passwort-Reset Link wurde an Sie verschickt', // 449
	'could.not.send.email' => 'Die Email konnte nicht verschickt werden', // 454
	'no.admin.account.email.password.reset' => 'Es kann kein Passwort-Reset Link für ein Adminkonto verschickt werden', // 460
	'user.account.not.found' => 'Benutzerkonto konnte nicht gefunden werden', // 464
	'email.password.reset.not.enabled' => 'Passwort Reset via Email ist nicht aktiviert. Bitte kontaktieren Sie den Administrator der Seite, um das für Sie zu tun', // 478
	'password.reset' => 'Passwort zurücksetzen', // 505
	'your.new.password' => 'Ihr neues Passwort', // 507
	'please.log.in.below' => 'Bitte melden Sie sich unterhalb an', // 509
	'change.password' => 'Passwort ändern', // 525
	'unable.to.change.password.?passwords.match' => 'Passwort konnte nicht geändert werden, weil die Passwörter nicht übereinstimmen', // 552
	'already.logged.in' => 'Sie sind schon angemeldet', // 574
	'provider.not.enabled.select.different.or.login' => 'Dieser Konto Provider ist nicht aktiviert. Bitte wählen Sie einen anderen aus, oder melden Sie sich hier direkt an.', // 590
	'click.yes.to.associate.account' => 'Klicken Sie "Ja", um dieses Provider Konto mit dem Benutzerkonto auf dieser Seite zu verbinden', // 622
	'user.account.associated.with.provider' => 'Ihr Benutzerkonto wurde erfolgreich mit dem Provider Konto verbunden', // 675
	'unable.to.associate.account.with.provider' => 'Es war leider nicht möglich Ihr Prvider Konto mit Ihrem Benutzerkonto zu verbinden.
        Bitte versichern Sie sich, dass noch kein anderes Benutzerkonto mit dem von Ihnen gewählten Provider Konto verbunden ist.', // 683
	'error.associating.account.with.provider' => 'Es gab einen Fehler beim Verbinden des angegebenen Provider Kontos mit Ihrem Benutzerkonto', // 691
	'twitter.no.email.retrive.support' => 'Zur erfolgreichen Verbindung Ihres Twitter Kontos mit Ihrem Benutzerkonto geben Sie jetzt bitte noch Ihre Email Adresse an', // 777
	'logged.in.but.account.emails.do.not.match' => 'Sie sind angemeldet, aber die Email Adresse Ihres Provider Kontos stimmt nicht mit der Email Adresse Ihres Benutzerkontos überein', // 807
	'retrieving.info.from.provider.failed.register.below' => 'Es gab Fehler beim Versuch die Provider Kontodaten abzurufen. Bitte registrieren Sie sich unterhalb', // 813

	// \classes\useradmin\controller\admin\user.php
	'user.administration' => 'User Verwaltung', // 43
	'edit.user' => 'User bearbeiten', // 81
	'delete.user' => 'User löschen', // 223
	'user.already.deleted' => 'User ist schon gelöscht', // 240

	// Orphan phrases
);
