<?php defined('SYSPATH') or die('No direct script access.');

// This file was generated by Kohana-I18nget, http://github.com/rafsoaken/kohana-i18nget

return array(
	// \views\useradmin\menu.php
	'user.admin' => 'Администрирование пользователей', // 9
	'my.profile' => 'Мой профиль', // 11
	'logout' => 'Выйти', // 12
	'register' => 'Регистрация', // 16
	'login' => 'Войти', // 17

	// \views\user\login.php
	'email.or.username' => 'Email или Имя пользователя', // 23
	'password' => 'Пароль', // 26
	'?forgot.password' => 'Забыли пароль?', // 27
	'remember.me' => 'Запомнить меня', // 38
	'?dont.have.account' => 'Нет учетной записи?', // 54
	'register.new.account' => 'Зарегистрируйтесь!', // 54
	'register.or.providerchange' => 'Чтобы зарегистрироваться, или войти под другой учетной записью - выберите сервис', // 57
    'login.using.provider' => 'Выберите провайдера авторизации',

	// \views\user\noaccess.php
	'access.denied' => 'Доступ запрещен', // 2
	'no.rights.to.access.functionality' => 'У вас нет необходимых прав, чтобы получить доступ к этому функционалу', // 4

	// \views\user\profile.php
	'edit.profile' => 'Редактировать профиль', // 4
	'delete.account' => 'Удалить учетную запись', // 5
	'user.profile' => 'Профиль пользователя', // 9
	'your.user.information' => 'Это ваши пользовательские данные', // 11
	'username' => 'Имя пользователя', // 13
	'email address' => 'Email', // 13
	'login.activity' => 'Активность', // 16
	'total.nbr.logins' => 'Общее число посещений', // 17
	'accounts.associated.with.profile' => 'Учетные записи, ассоциированные с вашей', // 23
	'additional.accountproviders' => 'Дополнительные сервисы авторизации', // 31
	'click.provider.icon.to.associate.account' => 'Кликните по иконке провайдера, чтобы ассоциировать его с вашей учетной записью', // 31

	// \views\user\profile_edit.php
	'roles' => 'Роли', // 19
	'role' => 'Роль', // 21
	'description' => 'Описание', // 21
	'save' => 'Сохранить', // 40

	// \views\user\register.php
	'?already.have.account' => 'Уже есть учетная запись?', // 5
	'login.here' => 'Войти здесь.', // 5
	'enter.info.to.register' => 'Заполните поля ниже, чтобы зарегистрироваться', // 7
	'register.account' => 'Создать новую учетную запись', // 35

	// \views\user\unregister.php
	'confirm.remove.user.account' => 'Подтвердите удаление учетной записи', // 2
	'?sure.to.remove.user.account' => 'Вы точно уверены, что хотите удалить свою учетную запись ?', // 10
	'yes' => 'Да', // 12
	'no' => 'Нет', // 13
	'confirm' => 'Подтвердить', // 15
	'cancel' => 'Отмена', // 19

	// \views\user\user_edit_form.php
	'allowed.usernames' => 'Можно использовать цифры, буквы, точку и прочерк. Длинна от 4 до 32 символов', // 2
	'email.address' => 'Email', // 3
	'allowed.passwords' => 'Пароль должен быть от 6 до 42 символов.', // 6
	'retype.password' => 'Пароль ещё раз', // 7

	// \views\user\reset\forgot.php
	'?forgot.password.or.username' => 'Забыли пароль или имя пользователя ?', // 3
	'send.password.resetlink' => 'Отправить мне письмо восстановления пароля', // 6
	'reset.password' => 'Сброс пароля', // 14

	// \views\user\reset\reset.php
	'account.email.address' => 'Email, на который была зарегистрирована учетная запись', // 10
	'password.reset.token' => 'Токен сброса пароля', // 14

	// \views\user\admin\delete.php
	'?delete.user' => 'Удалить пользователя?', // 3
	'?sure.to.delete.user' => 'Точно удалить пользователя ":user" ?', // 12
	'delete' => 'Удалить', // 16

	// \views\user\admin\edit.php
	'?edit.or.add.user' => 'Редактировать/добавить пользователя', // 18

	// \views\user\admin\index.php
	'?add.user' => 'Добавить пользователя', // 11
	'administer.users' => 'Управлять людьми', // 15
	'edit' => 'Редактировать', // 31
	'last.login' => 'Последний вход', // 54
	'nbr.of.logins' => 'Количество входов', // 55
	'identities' => 'Службы авторизации', // 58
	'actions' => 'Действия', // 60

	// \views\template\useradmin.php
	'module.page.title' => 'Useradmin для Kohana', // 15

	// \views\pagination\useradmin.php
	'first' => 'Первая', // 13
	'previous' => 'Предыдущая', // 19
	'next' => 'Следующая', // 35
	'last' => 'Последняя', // 41

	// \messages\register\user.php
	'username.already.registered' => 'Это имя пользователя уже занято, пожалуйста выберите другое', // 6
	'username.already.used' => 'Это имя пользователя уже используется.', // 7
	'email.invalid' => 'Этот Email выглядит подозрительно. Пожалуйста, используйте другой', // 10
	'email.already.used' => 'Этот Email занят', // 11
	'password.confirm.different' => 'Пароль и подтверждение не совпадают', // 20

	// \classes\useradmin\helper\format.php
	'never' => 'никогда', // 33
	'one.second.ago' => 'секунду назад', // 38
	'seconds.ago' => 'секунд назад', // 38
	'one.minute.ago' => 'минуту назад', // 42
	'minutes.ago' => 'минут назад', // 46
	'one.hour.ago' => 'час назад', // 50
	'hours.ago' => 'часов назад', // 54
	'yesterday' => 'вчера', // 58
	'days.ago' => 'дней назад', // 62
	'one.month.ago' => 'месяц назад', // 67
	'months.ago' => 'месяцев назад', // 67
	'one.year.ago' => 'год назад', // 72
	'years.ago' => 'лет назад', // 72

	// \classes\useradmin\controller\user.php
	'values.saved' => 'Значения сохранены', // 161
	'error.values.could.not.be.saved' => 'Ошибка: значения не могут быть сохранены', // 170
	'user.registration' => 'Регистрация', // 208
	'captcha.incorrect' => 'Текст CAPTCHA введен неверно', // 235
	'please.try.again' => 'Пожалуйста, попробуйте ещё раз', // 235
	'close.user.account' => 'Удалить учетную запись', // 277
	'user.deleted' => 'Пользователь удален', // 308
	'forgot.password' => 'Забыли пароль ?', // 424
	'account.password.reset' => 'Пароль учетной записи сброшен', // 436
	'email.password.reset.message.body' => 'Вы запросили сброс пароля. Его можно поменять по ссылке

:reset_token_link

Если эта ссылка не работает, попробуйте перейти по этой

:reset_link

и скопировать в поле токена эту комбинацию:
:reset_token

Ваше имя учетной записи: :username
', // 441
	'password.reset.email.sent' => 'Письмо сборса пароля отправлено', // 457
	'could.not.send.email' => 'Невозможно отправить письмо сброса пароля', // 462
	'no.admin.account.email.password.reset' => 'Пароль администратора сбросить нельзя', // 469
	'user.account.not.found' => 'Невозможно найти учетную запись с таким именем', // 473
	'email.password.reset.not.enabled' => 'Сброс пароля отклчен. Пожалуйста, свяжитесь с администрацией.', // 488
	'password.reset' => 'Сброс пароля', // 517
	'your.new.password.is :password' => 'Ваш пароль был изменен на: ":password".', // 519
	'please.log.in.below' => 'Пожалуйста, войдите, используя форму ниже', // 521
	'change.password' => 'Сменить пароль', // 538
	'unable.to.change.password.?passwords.match' => 'Невозможно изменить пароль. Пожалуйста, проверьте что пароль совпадает с подтверждением', // 565
	'already.logged.in' => 'Вы уже вошли на сайт', // 587
	'provider.not.enabled.select.different.or.login' => 'Этот провайдер отключен. Пожалуйста, используйте другого или войдите с помощью Email и пароля', // 603
	'click.yes.to.associate.account' => 'Нажмите Да для подтверждения ассоциирования службы с учетной записью', // 635
	'user.account.associated.with.provider' => 'Ваша учетная запись была ассоциирована со службой авторизации', // 688
	'unable.to.associate.account.with.provider' => 'Мы не смогли ассоциировать вашу учетную запись с этим сервисом авторизации.
	    Возможно, аккаунт на этом сервисе уже был ассоциирован с другой учетной записью, в то время как мы можем разрешить только одну такую связь.
	', // 696
	'error.associating.account.with.provider' => 'Произошла ошибка при ассоциации сервиса с вашей учетной записью', // 704
	'no.email.retrive.support' => 'Мы не смогли получить ваш Email. Пожалуйста, зарегистрируйтесь через форму ниже или выберите другого провайдера', // 790
	'logged.in.but.account.emails.do.not.match' => 'Email, который мы получили от сервиса авторизации не совпадает с тем, что указан у нас.', // 820
	'retrieving.info.from.provider.failed.register.below' => 'Мы не смогли получить информацию от сервиса авторизации. Пожалуйста, войдите на сайт, используя форму ниже', // 826

	// \classes\useradmin\controller\admin\user.php
	'user.administration' => 'Управлять людьми', // 43
	'edit.user' => 'Редактировать пользователя', // 81
	'delete.user' => 'Удалить пользователя', // 223
	'user.already.deleted' => 'Пользователь уже удалён', // 240
    'password.invalid' => 'Неверный пароль',
    'password.not_empty' => 'Вы забыли ввести пароль',
    'username.invalid' => 'Пользователя с таким именем у нас нет',
    'username.not_empty' => 'Вы забыли ввести имя пользователя или e-mail',
    'matching.account.exists.for.provider' => 'С этим провайдером уже ассоциирована учетная запись',
    'please.complete.data.from.other.account' => 'Пожалуйста, заполните форму для продолжения регистрации'
	// Orphan phrases
);
